
help:
	@echo ""
	@echo "Available targets:"
	@echo ""
	@echo "install             will copy plugin to plugindirectory .homeassistant/custom_components"
	@echo ""

install:
	mkdir -p ~/.homeassistant/custom_components/switch
	cp custom_components/switch/knx.py ~/.homeassistant/custom_components/switch


