                                       # Home Assistant Standardkonfiguration laden
# https://www.home-assistant.io/integrations/default_config/
default_config:


frontend:
  themes: !include_dir_merge_named themes


# Media Player Integration


# TextToSpeech Integration
tts:
  - platform: google_translate
    language: 'de'


# KNX Integration
# https://www.home-assistant.io/integrations/knx/
xknx:
  tunneling:
    host: 192.168.178.29
  sensor:
    - name: Strom Leistung Bezug
      state_address: '5/5/42'
      type: power
      
    - name: Strom Leistung Lieferung
      state_address: '5/5/43'
      type: power
      
    - name: AB Temperatur Nord
      state_address: '5/6/7'
      type: temperature
      
    - name: AB Temperatur Sd
      state_address: '5/6/8'
      type: temperature
      
    - name: AB Helligkeit Ost
      state_address: '5/6/3'
      type: illuminance
      
    - name: AB Helligkeit Sd
      state_address: '5/6/4'
      type: illuminance
    
    - name: AB Helligkeit West
      state_address: '5/6/5'
      type: illuminance
      
    - name: AB Windgeschwindigkeit
      state_address: '5/6/0'
      type: wind_speed_ms
      
  binary_sensor:    
    - name: TagNacht
      state_address: '0/0/1'
