send:
  description: "Send arbitrary data directly to the KNX bus."
  fields:
    address:
      description: "Group address(es) to write to."
      example: "1/1/0"
    payload:
      description: "Payload to send to the bus. Integers are treated as DPT 1/2/3 payloads. For DPTs > 6 bits send a list. Each value represents 1 octet (0-255). Pad with 0 to DPT byte length."
      example: "[0, 4]"
    type:
      description: "Optional. If set, the payload will not be sent as raw bytes, but encoded as given DPT. Knx sensor types are valid values (see https://www.home-assistant.io/integrations/sensor.knx)."
      example: "temperature"
read:
  description: "Send GroupValueRead requests to the KNX bus. Response can be used from `knx_event` and will be processed in KNX entities."
  fields:
    address:
      description: "Group address(es) to send read request to. Lists will read multiple group addresses."
      example: "1/1/0"
event_register:
  description: "Add or remove single group address to knx_event filter for triggering `knx_event`s. Only addresses added with this service can be removed."
  fields:
    address:
      description: "Group address that shall be added or removed."
      example: "1/1/0"
    remove:
      description: "Optional. If `True` the group address will be removed. Defaults to `False`."
exposure_register:
  description: "Add or remove exposures to KNX bus. Only exposures added with this service can be removed."
  fields:
    address:
      description: "Required. Group address state or attribute updates will be sent to. GroupValueRead requests will be answered. Per address only one exposure can be registered."
      example: "1/1/0"
    type:
      description: "Required. Telegrams will be encoded as given DPT. 'binary' and all Knx sensor types are valid values (see https://www.home-assistant.io/integrations/sensor.knx)"
      example: "percentU8"
    entity_id:
      description: "Required. Entity id to be exposed."
      example: "light.kitchen"
      required: true
    attribute:
      description: "Optional. Attribute of the entity that shall be sent to the KNX bus. If not set the state will be sent. Eg. for a light the state is eigther “on” or “off” - with attribute you can expose its “brightness”."
      example: "brightness"
      required: false
    default:
      description: "Optional. Default value to send to the bus if the state or attribute value is None. Eg. a light with state “off” has no brightness attribute so a default value of 0 could be used. If not set (or None) no value would be sent to the bus and a GroupReadRequest to the address would return the last known value."
      example: "0"
    remove:
      description: "Optional. If `True` the exposure will be removed. Only `address` is required for removal."
