name: Pre-commit auto-update

on:
  schedule:
    - cron: "0 8 15 * *"
  # on demand
  workflow_dispatch:

jobs:
  auto-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Set up uv and Python
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
          python-version: "3.14"
      - name: Install dependencies
        run: uv sync --locked
      - name: Hook auto-update
        env:
          # new branch is created in create-pull-request step
          SKIP: no-commit-to-branch
        run: uv run --no-sync prek update
      - uses: peter-evans/create-pull-request@v8
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: update/pre-commit-hooks
          title: Update pre-commit hooks
          commit-message: "update pre-commit hooks"
          labels: |
            dependencies
          body: |
            Update versions of pre-commit hooks to latest version.
            Run tests locally to check for conflicts since PRs from GitHub Actions don't trigger workflows.
